//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benmoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPackingMaster
    {
        public int ProductPackingID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public int PackingTypeID { get; set; }
        public int Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal RP { get; set; }
        public byte CommandID { get; set; }
        public bool IsActive { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateIP { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateIP { get; set; }
    }
}
