//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benmoon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMaster
    {
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public int HSNSACodeID { get; set; }
        public string ProductImage { get; set; }
        public string ProductThumbImage { get; set; }
        public string Composition { get; set; }
        public string Benifits { get; set; }
        public string DirectionOfUse { get; set; }
        public short DisplayOrder { get; set; }
        public byte CommandID { get; set; }
        public bool IsActive { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateIP { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateIP { get; set; }
    }
}
